version: "3.8"

services:
  postgres:
    image: postgres:13
    restart: always
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - my-network
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  hasura:
    image: hasura/graphql-engine:v2.41.0
    restart: always
    container_name: hasura
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_PASSWORD}
    networks:
      - my-network

  client:
    container_name: toDoList_client
    restart: unless-stopped
    image: client-test
    build: 
      context: client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - my-network
    depends_on:
      - hasura

networks:
  my-network:
